### ISSUE TITLE
encoding issue with progress bar

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#429]
```
..ERROR:pyFAI.worker:error in integration; Out of memory; data.shape: (1,); data.size: 1; ai:; <pyFAI.test.test_worker.AzimuthalIntegratorMocked object at 0x7f339557f710>; csr:
E.......    aaa [          ]   7%  toto
======================================================================
ERROR: test_coverage (pyFAI.test.test_utils_shell.TestUtilShell)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/here/.local/lib/python3.5/site-packages/pyFAI/test/test_utils_shell.py", line 52, in test_coverage
    progressbar.update(10.5, "toto")
  File "/here/.local/lib/python3.5/site-packages/pyFAI/utils/shell.py", line 110, in update
    sys.stdout.write(line + " " * clean_size + "\r")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 18-23: ordinal not in range(256)

----------------------------------------------------------------------
Ran 267 tests in 121.209s

FAILED (errors=1, skipped=5)
Test suite failed
```

**Comment by vallsv** [comment]
I try to reproduce the problem without success.

Here is anyway a PR https://github.com/silx-kit/pyFAI/pull/431
Hope it can fix the issue.

**Comment by kif** [comment]
should be fixed ... @leguyader could you confirm the test passes.

**Comment by leguyader** [comment]
Tested and the problem remained. I then realized that the locale was not UTF-8. Setting LANG to en_US.UTF-8 and running ipython3 and the pyFAI.tests() again and everything works.

Cheers.

**Comment by vallsv** [comment]
Good to know. Then the problem is the console output, i guess.

**Comment by kif** [comment]
this needs to be noticed in the documentation before closing the bug. There is something similar for MacOSX where certain version have wrong "LANG"

**Comment by kif** [comment]
On Thu, 22 Sep 2016 11:22:45 -0700
Loïc Le Guyader <notifications@github.com> wrote:

> Tested and the problem remained. I then realized that the locale was not UTF-8. Setting LANG to en_US.UTF-8 and running ipython3 and the pyFAI.tests() again and everything works.
> 

Maybe the issue is if the console does not understand such character with large unicode index.

One solution would be to try to print such large square in a try block and replace it with "#" or "-" in the except. 

@vvalls what do you think of this ?

**Comment by vallsv** [comment]
If we can reach the console encoding, we have to do it

**Comment by leguyader** [comment]
Not sure if this helps but:
- with ```LANG=en_US```, ```sys.stdout.encoding``` returns ```ANSI_X3.4-1968```
- with ```LANG=en_US.UTF-8```, it returns ```UTF-8```
